include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SnowfallPrefs
SnowfallPrefs_FILES = SnowfallPrefsRootListController.m
SnowfallPrefs_FRAMEWORKS = UIKit
SnowfallPrefs_INSTALL_PATH = /Library/PreferenceBundles
SnowfallPrefs_CFLAGS = -fobjc-arc
SnowfallPrefs_LDFLAGS = -undefined dynamic_lookup

include $(THEOS_MAKE_PATH)/bundle.mk
