include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SnowfallPrefs
SnowfallPrefs_FILES = SnowfallPrefsRootListController.m
SnowfallPrefs_FRAMEWORKS = UIKit
SnowfallPrefs_PRIVATE_FRAMEWORKS = Preferences
SnowfallPrefs_INSTALL_PATH = /Library/PreferenceBundles
SnowfallPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
